server:
  port: 8888

spring:
  application:
    name: configserver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    config:
      server:
        git:
          uri: https://github.com/SpringMsaPr/springCloudConfigs.git
          clone-on-start: true
          default-label: main
    bus:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: busrefresh, health #env, info, refresh 등도 활용가능